version: '3.8'
services:
  web:
    build: 
      context: ./todolist-flask
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE_USER: chandra
      MYSQL_DATABASE_PASSWORD: Chandra@123
      MYSQL_DATABASE_DB: todo_db
      MYSQL_DATABASE_PORT: 3306
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Chandra@123
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
