#this is not working yet, only works building the docker images and containers manually while passing environment variables in the command line.

version: '3.8'
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: Chandra@123
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_HOST: '%'  # Allow root user to connect from any host
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: Chandra@123
      MYSQL_DATABASE_DB: todo_db
      MYSQL_DATABASE_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
